import { InsertLawyer } from "@shared/schema";

export const lawyerData: InsertLawyer[] = [
  {
    name: "Sarah Johnson",
    profileImage: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Specializing in complex immigration cases with over 15 years of experience. Fluent in Spanish and Portuguese. Sarah has successfully handled hundreds of cases ranging from family-based petitions to complex asylum claims and deportation defense.",
    practiceAreas: ["immigration_law", "family_law"],
    hourlyRate: 200,
    rating: 4.5,
    reviewCount: 124,
    location: "New York, NY",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "sarah.johnson@legalaid.com",
    contactPhone: "(212) 555-1234",
    address: "350 Fifth Avenue, Suite 4500, New York, NY 10118"
  },
  {
    name: "Michael Rodriguez",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Former prosecutor with 20+ years of experience. Specialized in handling complex criminal cases with a high success rate. Michael's background as a state prosecutor gives him unique insight into how the other side builds their cases.",
    practiceAreas: ["criminal_defense"],
    hourlyRate: 350,
    rating: 4.8,
    reviewCount: 212,
    location: "Chicago, IL",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: false,
    contactEmail: "michael.rodriguez@legalaid.com",
    contactPhone: "(312) 555-6789",
    address: "233 S Wacker Dr, Suite 8000, Chicago, IL 60606"
  },
  {
    name: "Amanda Chen",
    profileImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Compassionate family law attorney focusing on divorce, custody, and mediation. Certified mediator with a focus on collaborative solutions that prioritize children's wellbeing and equitable outcomes for all parties.",
    practiceAreas: ["family_law", "estate_planning"],
    hourlyRate: 175,
    rating: 3.9,
    reviewCount: 87,
    location: "Los Angeles, CA",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "amanda.chen@legalaid.com",
    contactPhone: "(310) 555-4321",
    address: "633 W 5th St, Suite 2800, Los Angeles, CA 90071"
  },
  {
    name: "James Williams",
    profileImage: "https://images.unsplash.com/photo-1556157382-97eda2d62296?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Harvard Law graduate specializing in corporate law, mergers & acquisitions, and business formation. James has advised Fortune 500 companies and startups alike on complex business transactions and regulatory compliance matters.",
    practiceAreas: ["business_law", "tax_law"],
    hourlyRate: 450,
    rating: 5.0,
    reviewCount: 156,
    location: "Boston, MA",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "james.williams@legalaid.com",
    contactPhone: "(617) 555-8765",
    address: "100 Federal St, 35th Floor, Boston, MA 02110"
  },
  {
    name: "Robert Thomas",
    profileImage: "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Dedicated to helping injury victims get the compensation they deserve. No win, no fee policy. Robert has recovered millions of dollars for clients injured in auto accidents, workplace incidents, and medical malpractice cases.",
    practiceAreas: ["personal_injury"],
    hourlyRate: 225,
    rating: 4.3,
    reviewCount: 79,
    location: "Houston, TX",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "robert.thomas@legalaid.com",
    contactPhone: "(713) 555-2468",
    address: "1221 McKinney St, Suite 4000, Houston, TX 77010"
  },
  {
    name: "Daniel Martinez",
    profileImage: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Expert in real estate transactions, commercial leasing, and property disputes. Former real estate broker with practical industry experience. Daniel represents buyers, sellers, developers, and lenders in all aspects of real estate law.",
    practiceAreas: ["real_estate_law", "business_law"],
    hourlyRate: 275,
    rating: 4.1,
    reviewCount: 64,
    location: "Miami, FL",
    experienceLevel: "mid",
    availableForConsultation: false,
    featured: false,
    contactEmail: "daniel.martinez@legalaid.com",
    contactPhone: "(305) 555-1357",
    address: "600 Brickell Ave, Suite 3600, Miami, FL 33131"
  },
  {
    name: "Emily Peterson",
    profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Specializing in intellectual property, copyright, trademark, and patent law for creative professionals and technology companies. Emily helps entrepreneurs protect their innovations and creative works in the digital marketplace.",
    practiceAreas: ["intellectual_property", "business_law"],
    hourlyRate: 325,
    rating: 4.7,
    reviewCount: 92,
    location: "San Francisco, CA",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "emily.peterson@legalaid.com",
    contactPhone: "(415) 555-9753",
    address: "555 California St, Suite 4000, San Francisco, CA 94104"
  },
  {
    name: "David Kim",
    profileImage: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Employment law specialist representing both employees and employers in workplace disputes, discrimination cases, and contract negotiations. David is known for his balanced approach and deep understanding of labor regulations.",
    practiceAreas: ["employment_law"],
    hourlyRate: 250,
    rating: 4.4,
    reviewCount: 108,
    location: "Seattle, WA",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "david.kim@legalaid.com",
    contactPhone: "(206) 555-3690",
    address: "1201 Third Ave, Suite 4900, Seattle, WA 98101"
  },
  {
    name: "Jessica Patel",
    profileImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Tax attorney specializing in individual and business tax planning, IRS disputes, and international tax matters. Jessica previously worked for the IRS, giving her valuable perspective on navigating complex tax challenges.",
    practiceAreas: ["tax_law", "business_law"],
    hourlyRate: 300,
    rating: 4.2,
    reviewCount: 73,
    location: "Washington, DC",
    experienceLevel: "senior",
    availableForConsultation: false,
    featured: false,
    contactEmail: "jessica.patel@legalaid.com",
    contactPhone: "(202) 555-8024",
    address: "1700 K St NW, Suite 800, Washington, DC 20006"
  },
  {
    name: "Christopher Lee",
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Estate planning attorney helping clients preserve wealth and protect loved ones through wills, trusts, and advance directives. Christopher takes a holistic approach to ensure your final wishes are honored and your legacy protected.",
    practiceAreas: ["estate_planning", "tax_law"],
    hourlyRate: 225,
    rating: 4.9,
    reviewCount: 118,
    location: "Atlanta, GA",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "christopher.lee@legalaid.com",
    contactPhone: "(404) 555-7119",
    address: "191 Peachtree St NE, Suite 3300, Atlanta, GA 30303"
  },
  {
    name: "Olivia Washington",
    profileImage: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Criminal defense lawyer focusing on DUI cases, drug offenses, and white-collar crime with a strong track record of case dismissals and reduced sentences. Olivia is deeply committed to protecting the constitutional rights of everyone accused of a crime.",
    practiceAreas: ["criminal_defense"],
    hourlyRate: 275,
    rating: 4.6,
    reviewCount: 132,
    location: "Philadelphia, PA",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "olivia.washington@legalaid.com",
    contactPhone: "(215) 555-6284",
    address: "1735 Market St, Suite 3000, Philadelphia, PA 19103"
  },
  {
    name: "Ryan Garcia",
    profileImage: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Personal injury attorney specializing in car accidents, slip and falls, and workplace injuries. Ryan fights tirelessly to ensure victims receive maximum compensation for medical bills, lost wages, and pain and suffering.",
    practiceAreas: ["personal_injury"],
    hourlyRate: 200,
    rating: 3.8,
    reviewCount: 56,
    location: "Denver, CO",
    experienceLevel: "junior",
    availableForConsultation: true,
    featured: false,
    contactEmail: "ryan.garcia@legalaid.com",
    contactPhone: "(303) 555-4917",
    address: "1700 Lincoln St, Suite 4000, Denver, CO 80203"
  },
  {
    name: "Sophia Miller",
    profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Immigration attorney passionate about helping families reunite, individuals secure asylum, and businesses navigate work visas and compliance. Sophia is multilingual and brings cultural sensitivity to every case she handles.",
    practiceAreas: ["immigration_law"],
    hourlyRate: 185,
    rating: 4.7,
    reviewCount: 91,
    location: "Dallas, TX",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "sophia.miller@legalaid.com",
    contactPhone: "(214) 555-3826",
    address: "2200 Ross Ave, Suite 5000, Dallas, TX 75201"
  },
  {
    name: "Jonathan Robinson",
    profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Corporate lawyer specializing in startups, venture capital, and technology companies. Jonathan helps entrepreneurs form companies, raise capital, and navigate regulatory challenges while protecting their interests.",
    practiceAreas: ["business_law", "intellectual_property"],
    hourlyRate: 400,
    rating: 4.3,
    reviewCount: 84,
    location: "Austin, TX",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "jonathan.robinson@legalaid.com",
    contactPhone: "(512) 555-7294",
    address: "500 W 2nd St, Suite 1800, Austin, TX 78701"
  },
  {
    name: "Michelle Wong",
    profileImage: "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Family law attorney with expertise in high-asset divorces, child custody disputes, and prenuptial agreements. Michelle approaches sensitive family matters with compassion while aggressively protecting her clients' rights and interests.",
    practiceAreas: ["family_law"],
    hourlyRate: 250,
    rating: 4.5,
    reviewCount: 103,
    location: "San Diego, CA",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "michelle.wong@legalaid.com",
    contactPhone: "(619) 555-0142",
    address: "600 B St, Suite 2100, San Diego, CA 92101"
  },
  {
    name: "Andrew Taylor",
    profileImage: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Real estate and construction law specialist dealing with development projects, contractor disputes, and commercial leasing. Andrew represents property owners, developers, and construction professionals in transactions and litigation.",
    practiceAreas: ["real_estate_law", "business_law"],
    hourlyRate: 295,
    rating: 4.0,
    reviewCount: 67,
    location: "Phoenix, AZ",
    experienceLevel: "senior",
    availableForConsultation: false,
    featured: false,
    contactEmail: "andrew.taylor@legalaid.com",
    contactPhone: "(602) 555-8631",
    address: "2 N Central Ave, Suite 2200, Phoenix, AZ 85004"
  },
  {
    name: "Rachel Foster",
    profileImage: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Employment lawyer representing employees in discrimination, harassment, and wrongful termination cases. Rachel has secured millions in settlements and verdicts for workers whose rights have been violated in the workplace.",
    practiceAreas: ["employment_law"],
    hourlyRate: 235,
    rating: 4.4,
    reviewCount: 89,
    location: "Minneapolis, MN",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "rachel.foster@legalaid.com",
    contactPhone: "(612) 555-3957",
    address: "80 S 8th St, Suite 4900, Minneapolis, MN 55402"
  },
  {
    name: "Thomas Reynolds",
    profileImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Intellectual property attorney focusing on patent prosecution, licensing, and litigation for technology and life sciences companies. Thomas has a background in engineering and helps inventors protect their innovations globally.",
    practiceAreas: ["intellectual_property"],
    hourlyRate: 375,
    rating: 4.8,
    reviewCount: 116,
    location: "Raleigh, NC",
    experienceLevel: "senior",
    availableForConsultation: true,
    featured: true,
    contactEmail: "thomas.reynolds@legalaid.com",
    contactPhone: "(919) 555-2746",
    address: "150 Fayetteville St, Suite 2300, Raleigh, NC 27601"
  },
  {
    name: "Maria Sanchez",
    profileImage: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Dedicated immigration attorney helping families navigate the complex immigration system, from visa applications to naturalization. Maria has personal experience with the immigration process and brings empathy to every client interaction.",
    practiceAreas: ["immigration_law", "family_law"],
    hourlyRate: 190,
    rating: 3.9,
    reviewCount: 72,
    location: "Orlando, FL",
    experienceLevel: "junior",
    availableForConsultation: true,
    featured: false,
    contactEmail: "maria.sanchez@legalaid.com",
    contactPhone: "(407) 555-1982",
    address: "200 S Orange Ave, Suite 2600, Orlando, FL 32801"
  },
  {
    name: "Eric Wilson",
    profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    bio: "Criminal defense attorney and former public defender representing clients facing misdemeanors and felonies. Eric is committed to ensuring that every person receives a fair trial and zealous representation regardless of resources.",
    practiceAreas: ["criminal_defense"],
    hourlyRate: 200,
    rating: 4.6,
    reviewCount: 98,
    location: "Portland, OR",
    experienceLevel: "mid",
    availableForConsultation: true,
    featured: false,
    contactEmail: "eric.wilson@legalaid.com",
    contactPhone: "(503) 555-6749",
    address: "111 SW 5th Ave, Suite 3800, Portland, OR 97204"
  }
];
